//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Publication.rc
//
#define IDNOUVEAU                       8
#define IDMODIFY                        9
#define IDADD                           10
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PUBLICTYPE                  129
#define IDD_NEW_PUBLICATION             130
#define IDD_SELECTION_DIRECTORY         131
#define IDI_CATEGORIE_SELECT            135
#define IDI_CATEGORIE                   136
#define IDI_ROOT                        138
#define IDI_DOCUMENT                    139
#define IDD_WAIT_DIALOG                 141
#define IDD_LOGIN                       142
#define IDD_PROPR_CATEGORIE             144
#define IDD_RECHERCHE_AUTEUR            150
#define IDD_AJOUTER_AUTEUR              155
#define IDD_NEW_CATEGORIE               158
#define IDD_AJOUTER_SUJET               159
#define IDD_RECHERCHE_SUJET             160
#define IDD_AJOUTER_TYPE                161
#define IDD_RECHERCHE_TYPE              162
#define IDD_AJOUTER_MOT_CLEF            163
#define IDD_RECHERCHE_MOT_CLEF          164
#define IDD_AJOUTER_GENRE               165
#define IDD_RECHERCHE_GENRE             166
#define IDD_RECHERCHE_CATEGORIE         167
#define IDD_AJOUTER_PUBLICATION_1       172
#define IDD_AJOUTER_PUBLICATION_2       173
#define IDD_AJOUTER_PUBLICATION_3       174
#define IDD_AJOUTER_PUBLICATION_4       175
#define IDD_AJOUTER_PUBLICATION_2BIS    176
#define IDD_AJOUTER_PUBLICATION_1BIS    177
#define IDD_AJOUTER_PUBLICATION_3BIS    178
#define IDD_AJOUTER_PUBLICATION_4BIS    179
#define IDD_RECHERCHE_DOCUMENT          180
#define IDD_RECHERCHE_AVANCE_DOCUMENT   181
#define IDD_NEW_UTILISATEUR             182
#define IDD_RECHERCHE_UTILISATEUR       183
#define IDD_MODIFIER_UTILISATEUR        184
#define IDD_MODIFIER_PASSWORD           185
#define IDD_LISTE_UTILISATEUR           186
#define IDD_OPTION_BASE                 187
#define IDD_OPTION_BASE_GAL             188
#define IDR_MENU_CONTEXT_TREEVW         188
#define IDI_ICON1                       191
#define IDC_NOM_BASE                    1000
#define IDC_ADDCATEGORIE                1000
#define IDC_Nationalite                 1000
#define IDC_NOM_SAUVEGARDE              1001
#define IDLANCERECHERCHE                1001
#define IDC_REPERTOIRE_SAUVEGARDE       1003
#define IDC_BUTTON1                     1004
#define IDC_EFFACER                     1004
#define IDC_REMOVE_DE_PUB               1005
#define IDC_BUTTON_AUCUN                1005
#define IDC_ROOTNAME                    1006
#define IDC_REMOVE_ALL_ELEMENT          1006
#define IDC_PASSWORD1                   1007
#define IDC_PASSWORD2                   1008
#define IDC_TREE_REPERTOIRE             1015
#define IDC_NOM_REPERTOIRE              1017
#define IDC_DISQUE                      1021
#define IDC_COMBO1                      1022
#define IDC_AUTHOR_NATIONALITY          1022
#define IDC_PROGRES_BAR                 1023
#define IDC_ACTION                      1025
#define IDC_LOGIN                       1027
#define IDC_PASSWORD                    1028
#define IDC_NOM_AUTEUR                  1028
#define IDC_CATEGORIE_NAME              1029
#define IDC_SUJET                       1029
#define IDC_NOUVEAU_PASSWORD_2          1029
#define IDC_LOGIN_NAME                  1030
#define IDC_TYPE                        1030
#define IDC_ENTER_DATE                  1031
#define IDC_UPDATE_BUTTON               1032
#define IDC_NOM_CATEGORIE               1033
#define IDC_LOGIN_CAT                   1034
#define IDC_DATE_ENTREE                 1035
#define IDC_MODIFY_BUTTON               1036
#define IDC_Nom                         1050
#define IDC_NomAuteur                   1051
#define IDC_Prenom                      1052
#define IDC_PrenomAuteur                1053
#define IDC_Nation                      1054
#define IDC_MODIFIER                    1058
#define IDC_LIST_AUTEUR                 1059
#define IDC_IMPRIMER                    1059
#define IDC_AUTHOR_NAME                 1060
#define IDC_AUTHOR_PRENAME              1061
#define IDC_AUTHOR_NAISSANCE            1062
#define IDC_AUTHOR_MORT                 1063
#define IDC_AUTHOR_COMPLEMENT           1064
#define IDC_SUJET_NAME                  1065
#define IDC_LIST_SUJET                  1066
#define IDC_NomSujet                    1067
#define IDC_TYPE_NAME                   1068
#define IDC_NomType                     1069
#define IDC_LIST_TYPE                   1070
#define IDC_KEY_NAME                    1071
#define IDC_NomKeyName                  1072
#define IDC_LIST_KEYNAME                1073
#define IDC_GENRE_NAME                  1074
#define IDC_NomGenre                    1075
#define IDC_LIST_GENRE                  1076
#define IDC_NomCategorie                1077
#define IDC_AFFICHER                    1078
#define IDC_LIST_CATEGORIE              1079
#define IDC_UtilisantEntrant            1080
#define IDC_PROPRIETE                   1083
#define IDC_NomLogin                    1085
#define IDC_EDIT_TITRE_DOCUMENT         1101
#define IDC_BUTTON_ADD_AUTEUR           1102
#define IDC_BUTTON_ADD_SUJET            1103
#define IDC_LISTE_SUJET                 1104
#define IDC_LISTE_GENRE                 1105
#define IDC_BUTTON_ADD_GENRE            1106
#define IDC_LISTE_TYPE                  1107
#define IDC_BUTTON_ADD_TYPE             1108
#define IDC_SEARCH_FICHIER              1109
#define IDC_CHECK_LINK                  1110
#define IDC_EDIT_FILENAME               1111
#define IDC_EDIT_RESUME_DOC             1112
#define IDC_EDIT_FILENAME_BASE          1112
#define IDC_LIST_MOT_CLEF               1113
#define IDC_LIST_ALL_MOT_CLEF           1114
#define IDC_DANS_LISTE_PUB              1115
#define IDC_ADD_MOT_CLEFS               1116
#define IDC_BUTTON_OUVRIR               1117
#define IDC_NomDocument                 1119
#define IDC_GENRE                       1120
#define IDC_LIST_DOCUMENT               1121
#define IDC_AJOUTER_MOTCLES             1124
#define IDC_RETIRER_MOTCLES             1125
#define IDC_MOT_CLEF                    1126
#define IDC_NomMotClef                  1127
#define IDC_NOM_UTLISATEUR              1128
#define IDC_CHECK_ADD_ELEMENT           1131
#define IDC_CHECK_MODIFIER_ELEMENT      1132
#define IDC_CHECK_SUPPRIMER_ELEMENT     1133
#define IDC_CHECK_ADD_UTILISATEUR       1134
#define IDC_CHECK_MODI_DROIT_UTILISATEUR 1135
#define IDC_CHECK_PROP_BASE             1136
#define IDC_BUTTON_TOUS                 1137
#define IDC_CHECK_SUPPR_UTILISATEUR     1138
#define IDC_LIST_UTILISATEUR            1139
#define IDC_ANCIEN_PASSWORD             1140
#define IDC_NOUVEAU_PASSWORD            1141
#define IDC_REPERTOIRE_RACINE           1145
#define IDC_MODIFIER_CAT                1146
#define IDC_VERSION                     1147
#define IDC_CHECK_COPY                  1148
#define IDC_CHECK_ERASE                 1149
#define IDC_REPERTOIRE_BASE             1150
#define IDC_MODIFIER_REP_BASE           1151
#define ID_CATEGORIE_AJOUTER            32774
#define ID_CATEGORIE_SUPPRIMER          32775
#define ID_CATEGORIE_RECHERCHER         32776
#define ID_CATEGORIE_PROPRIETES         32778
#define ID_PUBLICATION_AJOUTER          32779
#define ID_PUBLICATION_SUPPRIMER        32780
#define ID_PUBLICATION_RECHERCHER       32781
#define ID_PUBLICATION_RECHERCHEAVD     32783
#define ID_PUBLICATION_OUVRIR           32784
#define ID_AUTEUR_AJOUTER               32788
#define ID_AUTEUR_RECHERCHER            32790
#define ID_SUJET_AJOUTER                32793
#define ID_SUJET_RECHERCHER             32794
#define ID_TYPE_AJOUTER                 32796
#define ID_TYPE_RECHERCHER              32798
#define ID_MOT_CLEFS_RECHERCHER         32800
#define ID_MOT_CLEFS_AJOUTER            32801
#define ID_GENRE_AJOUTER                32802
#define ID_GENRE_RECHERCHER             32803
#define ID_UTILISATEUR_AJOUTER          32804
#define ID_UTILISATEUR_RECHERCHER       32805
#define ID_UTILISATEUR_LISTEDESUTILISATEURS 32806
#define ID_UTILISATEUR_MOTDEPASSE       32807
#define ID_OPTIONS_PROPRIETSDELABASE    32808
#define ID_OPTIONS_PROPRIETE_BASE       32809
#define ID_OPTIONS_BASE                 32809
#define ID_OPTIONS_MODIFIERPROPRITS     32810
#define ID_OPTIONS_MODIFIER_PROPRIETE   32811
#define ID_AUTEUR_LISTE_NATION          32813
#define ID_PUBLICATION_PROP             32814
#define ID_OPTIONS_GENERALE             32815
#define ID_OPTION_UPDATE_BASE           32816
#define ID_SSMENU_SUPPR                 32819
#define ID_SSMENU_PROPRIETE             32820
#define StaticCaption                   65535
#define ID_GROUPBOX_DROIT               65535
#define ID_STATIC_LOGIN                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
